### PR TITLE
Avatar Loading Fail Fallback

### LINKED ISSUE #8835: [Bug]Scenes stopped loading when using the Alex avatar

### PR DESCRIPTION
**Pull request by HexaField**
Rework avatar loading to be safer by adding fallback to randomized avatars

### <samp>🤖 Generated by Copilot at 57fb289</samp>

No summary available (Limit exceeded: required to process 53613 tokens, but only 50000 are allowed per call)

## References
closes #8835

### <samp>🤖 Generated by Copilot at 57fb289</samp>

No walkthrough available (Limit exceeded: required to process 53613 tokens, but only 50000 are allowed per call)

### <samp>🤖 Generated by Copilot at 273fe51</samp>

> _Sing, O Muse, of the mighty refactorings_
> _That the skilled programmers wrought on the code_
> _To improve the avatars of the users_
> _And the state of the virtual world._

## QA Steps
_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

## Checklist
- If this PR is still a WIP, convert to a draft
- When this PR is ready, mark it as "Ready for review"
- [ensure all checks pass](https://github.com/etherealengine/etherealengine/wiki/Testing-&-Contributing)
- Changes have been manually QA'd 
- Changes reviewed by at least 2 approved reviewers

### CODE REVIEW

**Review by barankyle — APPROVED** [review]

File: packages/engine/src/avatar/state/AvatarNetworkState.tsx [hunk 1]
```diff
@@ -74,7 +76,31 @@ export const AvatarState = defineState({
...
+        AvatarState.updateUserAvatarId(randomAvatar.id)
+      })
+  },
+
+  updateUserAvatarId(avatarId: string) {
+    Engine.instance.api
+      .service(userPath)
+      .patch(Engine.instance.userID, { avatarId: avatarId })
+      .then(() => {
+        dispatchAction(
```
Comment (speigg) [inline packages/engine/src/avatar/state/AvatarNetworkState.tsx:96]: I dont believe we really need both of these mechanisms. Can we just standardize on listenting for avatar id changes via the feather hooks?

File: packages/engine/src/avatar/state/AvatarNetworkState.tsx [hunk 2]
```diff
@@ -96,24 +122,40 @@ const AvatarReactor = React.memo(({ entityUUID }: { entityUUID: EntityUUID }) =>
   useEffect(() => {
     if (!state.avatarID.value) return
 
+    let aborted = false
+
     Engine.instance.api
       .service(avatarPath)
       .get(state.avatarID.value)
       .then((avatarDetails) => {
+        if (aborted) return
```
Comment (speigg) [inline packages/engine/src/avatar/state/AvatarNetworkState.tsx:131]: We should be passing down a AbortSignal all the way to the fetch() request, so that network requests can be cancelled when they are no longer necessary

**Review by speigg — APPROVED** [review]

File: packages/engine/src/avatar/state/AvatarNetworkState.tsx (hunk 1 above)
Comment (HexaField) [reply packages/engine/src/avatar/state/AvatarNetworkState.tsx:96]: this action is what drives our event sourcing, thus it must be persisted to our cached actions

File: packages/engine/src/avatar/state/AvatarNetworkState.tsx (hunk 2 above)
Comment (HexaField) [reply packages/engine/src/avatar/state/AvatarNetworkState.tsx:131]: yes, can do in a follow up when we have better tooling
