### PR TITLE
fix(tests): network authority & ownerships

### LINKED ISSUE #7673: Full Network Authority & Ownership
Network authority & ownership is almost completely implemented, with only transferring authority left. 

Most of the logic exists in `WorldNetworkActionReceptor.ts` and previous associated tests working in `WorldNetworkActionReceptor.test.ts`

Conceptually, ownership should never change, and is denoted by the `userId` that created a network object. Authority is allowed to change, at the behest of the object's owner, or current authority, denoted by `peerId`.  The implementation is fairly self explanatory, with `receiveRequestAuthorityOverObject` and `receiveTransferAuthorityOfObject` being the handshake actions necessary.

### PR DESCRIPTION
**Pull request by aditya-mitra**
## Summary

Rewrote the tests for _transfer ownership of objects_ in [WorldNetworkActionReceptor.test.ts](https://github.com/EtherealEngine/etherealengine/blob/dev/packages/engine/src/networking/functions/WorldNetworkActionReceptor.test.ts)

## References

Closes #7673 

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] [ensure all checks pass](https://github.com/etherealengine/etherealengine/wiki/Testing-&-Contributing)
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

The tests seem to be passing now

image

### CODE REVIEW

File: packages/engine/src/networking/functions/WorldNetworkActionReceptor.ts [hunk 1]
```diff
@@ -121,6 +121,7 @@ const receiveRequestAuthorityOverObject = (
 
   dispatchAction(
     WorldNetworkAction.transferAuthorityOfObject({
+      $from: action.$from,
```
Comment (HexaField) [inline packages/engine/src/networking/functions/WorldNetworkActionReceptor.ts:124]: This is unnecessary, see above.

File: packages/engine/src/networking/functions/WorldNetworkActionReceptor.test.ts [hunk 2]
```diff
@@ -184,142 +185,71 @@ describe('WorldNetworkActionReceptors', () => {
...
+
+      assert.equal(networkObjectEntitiesBefore.length, 1)
+      assert.equal(networkObjectOwnedEntitiesBefore.length, 0)
+
+      assert.equal(getComponent(networkObjectEntitiesBefore[0], NetworkObjectComponent).ownerId, hostUserId)
+      assert.equal(getComponent(networkObjectEntitiesBefore[0], NetworkObjectComponent).authorityPeerID, peerID)
+
+      WorldNetworkActionReceptor.receiveRequestAuthorityOverObject(
+        WorldNetworkAction.requestAuthorityOverObject({
+          $from: hostUserId, // from host
```
Comment (HexaField) [inline packages/engine/src/networking/functions/WorldNetworkActionReceptor.test.ts:229]: we should be passing in `userId` here

**Review by HexaField — CHANGES_REQUESTED** [review]

File: packages/engine/src/networking/functions/WorldNetworkActionReceptor.test.ts (hunk 2 above)
Comment (aditya-mitra) [reply packages/engine/src/networking/functions/WorldNetworkActionReceptor.test.ts:229]: I think passing `userId` will not do the transfer because the `receiveTransferAuthorityOfObject()` function is checking if action's [`$from === ownerId`](https://github.com/EtherealEngine/etherealengine/blob/dev/packages/engine/src/networking/functions/WorldNetworkActionReceptor.ts#L135)

**Review by HexaField — APPROVED** [review]
