### PR TITLE
fix: Mediacomponent loop

### LINKED ISSUE #8565: [Bug]: MediaComponent doesn't loop when there is only one track
https://github.com/EtherealEngine/etherealengine/blob/b261be8fc81a157b63180b779581a74a2bc99283/packages/engine/src/scene/components/MediaComponent.ts#L344-L352

`getNextTrack` is called when there is a change in `[media.resources, media.track]`.
`getNextTrack` returns the same trackId when:
- When there is only one track and `playMode` is set to loop
- there are multiple tracks and `playMode` is set to `PlayMode.singleloop`

When this happens, `media.track` is not changed and the above hook is not triggered. Hence the media stops after one playback.

### PR DESCRIPTION
**Pull request by CITIZENDOT**
### <samp>🤖 Generated by Copilot at e7aa251</samp>

The pull request enhances the media component functionality by improving the track switching logic and refactoring the `getNextTrack` function. It also reduces code duplication by moving the `getNextTrack` function from `VolumetricComponent.ts` to `MediaComponent.ts` and updating the `VolumetricReactor` function accordingly.

## References
closes #8565

### <samp>🤖 Generated by Copilot at e7aa251</samp>

*  Removed unused `ComponentType` import from `MediaComponent.ts` and `VolumetricComponent.ts` ([link](https://github.com/EtherealEngine/etherealengine/pull/8909/files?diff=unified&w=0#diff-0b05e36919188e649d61cc405c4bcb5c9c9b066aa2cf2b938becb901aabea59cL38), [link](https://github.com/EtherealEngine/etherealengine/pull/8909/files?diff=unified&w=0#diff-488521cee868606ef11e398a540128d8c0f8c7d535547d76e49778e16e2b029bL40))
*  Added `ended` property to `MediaComponent` schema to track media track completion ([link](https://github.com/EtherealEngine/etherealengine/pull/8909/files?diff=unified&w=0#diff-0b05e36919188e649d61cc405c4bcb5c9c9b066aa2cf2b938becb901aabea59cR140))
*  Modified `MediaReactor` and `VolumetricReactor` functions to check `ended` property before changing track and reset it after changing track ([link](https://github.com/EtherealEngine/etherealengine/pull/8909/files?diff=unified&w=0#diff-0b05e36919188e649d61cc405c4bcb5c9c9b066aa2cf2b938becb901aabea59cR334-R339), [link](https://github.com/EtherealEngine/etherealengine/pull/8909/files?diff=unified&w=0#diff-488521cee868606ef11e398a540128d8c0f8c7d535547d76e49778e16e2b029bL160-R161))
*  Refactored `getNextTrack` function to take current track, track count, and play mode as parameters and moved it from `VolumetricComponent.ts` to `MediaComponent.ts` for reusability ([link](https://github.com/EtherealEngine/etherealengine/pull/8909/files?diff=unified&w=0#diff-0b05e36919188e649d61cc405c4bcb5c9c9b066aa2cf2b938becb901aabea59cL506-R532), [link](https://github.com/EtherealEngine/etherealengine/pull/8909/files?diff=unified&w=0#diff-488521cee868606ef11e398a540128d8c0f8c7d535547d76e49778e16e2b029bL260-L279), [link](https://github.com/EtherealEngine/etherealengine/pull/8909/files?diff=unified&w=0#diff-488521cee868606ef11e398a540128d8c0f8c7d535547d76e49778e16e2b029bL55-R54))
*  Modified `updateMediaElement` function to use `getNextTrack` function with correct arguments, set `ended` property on media element `ended` event, and call media element `play` method if not paused ([link](https://github.com/EtherealEngine/etherealengine/pull/8909/files?diff=unified&w=0#diff-0b05e36919188e649d61cc405c4bcb5c9c9b066aa2cf2b938becb901aabea59cL380-R387), [link](https://github.com/EtherealEngine/etherealengine/pull/8909/files?diff=unified&w=0#diff-0b05e36919188e649d61cc405c4bcb5c9c9b066aa2cf2b938becb901aabea59cL389-R400), [link](https://github.com/EtherealEngine/etherealengine/pull/8909/files?diff=unified&w=0#diff-0b05e36919188e649d61cc405c4bcb5c9c9b066aa2cf2b938becb901aabea59cL417-R432))

### <samp>🤖 Generated by Copilot at e7aa251</samp>

> _To switch tracks for media components_
> _The logic was not very elegant_
> _So they refactored `getNextTrack`_
> _And moved it to `MediaComponent`'s stack_
> _And made it more generic and relevant_

## QA Steps
_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

## Checklist
- If this PR is still a WIP, convert to a draft
- When this PR is ready, mark it as "Ready for review"
- [ensure all checks pass](https://github.com/etherealengine/etherealengine/wiki/Testing-&-Contributing)
- Changes have been manually QA'd 
- Changes reviewed by at least 2 approved reviewers

### CODE REVIEW

File: packages/engine/src/scene/components/MediaComponent.ts [hunk 1]
```diff
@@ -331,6 +331,12 @@ export function MediaReactor() {
 
   useEffect(
     function updateMediaElement() {
+      if (!media.ended.value) {
+        // If current track is not ended, don't change the track
+        return
```
Comment (speigg) [inline packages/engine/src/scene/components/MediaComponent.ts:336]: how would one force a certain track to play?

Comment (CITIZENDOT) [reply packages/engine/src/scene/components/MediaComponent.ts:336]: We can't do that. We can't do that currently as well.

Comment (CITIZENDOT) [reply packages/engine/src/scene/components/MediaComponent.ts:336]: Shall I remove it?

**Review by dinomut1 — APPROVED** [review]
