### PR TITLE
Load Percentage Calculation and Dynamic Loading Refactor

### LINKED ISSUE #7115: [Story]: Loading progress uses sum of all asset progress
Loading progress is incorrect. It jump from 0% to  (70% between 90%) suddenly, not reflecting the real progress.

### PR DESCRIPTION
**Pull request by AidanCaruso**
## Summary

- Use current load progress in bytes out of total bytes to calculate load percentages
- React to current load progress set to `SceneAssetPendingTagComponent` via the loader function in `ModelComponent`.

## References

closes #7115

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] [ensure all checks pass](https://github.com/XRFoundation/XREngine/wiki/Testing-&-Contributing)
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

### CODE REVIEW

File: packages/engine/src/scene/components/ModelComponent.ts [hunk 1]
```diff
@@ -101,10 +105,19 @@ function ModelReactor({ root }: EntityReactorProps) {
...
+            const loadedAsset = await AssetLoader.loadAsync(
+              model.src,
+              {
+                ignoreDisposeGeometry: model.generateBVH,
+                uuid
+              },
+              (onprogress) => {
+                if (hasComponent(entity, SceneAssetPendingTagComponent)) {
+                  setComponent(entity, SceneAssetPendingTagComponent, onprogress.loaded)
+                  getComponent(entity, SceneAssetPendingTagComponent).loadedAmount = onprogress.loaded
```
Comment (HexaField) [inline packages/engine/src/scene/components/ModelComponent.ts:117]: this should read
```ts
setComponent(entity, SceneAssetPendingTagComponent, { loadedAmount: onprogress.loaded })
```

instead of 
```ts
setComponent(entity, SceneAssetPendingTagComponent, onprogress.loaded)
getComponent(entity, SceneAssetPendingTagComponent).loadedAmount = onprogress.loaded
```

File: packages/engine/src/scene/functions/loaders/ModelFunctions.ts [hunk 2]
```diff
@@ -15,5 +21,5 @@ export const deserializeModel: ComponentDeserializeFunction = (
   /**
    * Add SceneAssetPendingTagComponent to tell scene loading system we should wait for this asset to load
    */
-  if (!getState(EngineState).sceneLoaded.value) setComponent(entity, SceneAssetPendingTagComponent, true)
+  addComponent(entity, SceneAssetPendingTagComponent)
```
Comment (HexaField) [inline packages/engine/src/scene/functions/loaders/ModelFunctions.ts:24]: setComponent is fine here

**Review by HexaField — CHANGES_REQUESTED** [review]

File: packages/engine/src/scene/components/ModelComponent.ts (hunk 1 above)
Comment (AidanCaruso) [reply packages/engine/src/scene/components/ModelComponent.ts:117]: Ah yes was going to fix this. Weird mistake I made with setcomponent.

File: packages/xrui/core/WebLayer.ts [hunk 3]
```diff
@@ -25,6 +34,37 @@ export class WebLayer {
     target: false
   }
 
+  //Only supports digits right now
+  //TO DO: Add alphabetical range support, specific characters
+  prerasterizedRange = [] as number[]
+  prerasterizedImages: Map<number, string> = new Map()
+
+  async prerasterizeRange() {
+    this.manager.prerasterized = true
```
Comment (speigg) [inline packages/xrui/core/WebLayer.ts:43]: this is a global state; won't this have side-effects for things that aren't prerasterized ?

**Review by speigg — CHANGES_REQUESTED** [review]

File: packages/xrui/core/WebLayer.ts (hunk 3 above)
Comment (AidanCaruso) [reply packages/xrui/core/WebLayer.ts:43]: Yes, I'm going to change this to a parameter that can be passed into the manager's functions as an argument.

File: packages/client-core/src/systems/LoadingUISystem.tsx [hunk 4]
```diff
@@ -124,8 +164,14 @@ export default async function LoadingUISystem(world: World) {
...
     const loadingState = getState(LoadingSystemState).loadingScreenOpacity
+    defaultColor.set(getAppTheme()!.textColor)
+    mainThemeColor.set(themeColors.alternate)
+    xrui.rootLayer.traverseLayersPreOrder((layer: WebLayer3D) => {
+      const mat = layer.contentMesh.material as MeshBasicMaterial
+      mat.color.lerpColors(defaultColor, mainThemeColor, engineState.loadingProgress.value * 0.01)
+    })
 
-    transition.update(world.deltaSeconds, (opacity) => {
+    /*transition.update(world.deltaSeconds, (opacity) => {
```
Comment (AidanCaruso) [inline packages/client-core/src/systems/LoadingUISystem.tsx:174]: This has been temporarily commented out for debugging, to prevent the loading screen from fading out.

**Comment by speigg** [comment]
@cla-bot check

**Comment by HexaField** [comment]
Now also fixes dynamic load function. Disabled prerasterization until XRUI is refactored.

**Review by speigg — APPROVED** [review]
